version: 1
disable_existing_loggers: True
formatters:
  fmt_no_colors:
    '()': 'logging.Formatter'
    format: '%(asctime)s %(levelname)8s %(name)s %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  fmt_colors:
    '()': 'ext://coloredlogs.ColoredFormatter'
    format: '%(asctime)s %(levelname)8s %(name)s %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
    field_styles:
      asctime:
        color: magenta
      name:
        color: blue
        bold: True
      levelname:
        color: cyan
        bold: True
    level_styles:
      info:
        color: cyan
      warning:
        color: yellow
      debug:
        color: green
      error:
        color: red
      critical:
        color: red
        bold: True
handlers:
  hnd_file_root:
    class: logging.FileHandler
    filename: root.log
    encoding: utf-8
    formatter: fmt_no_colors
    level: INFO
  hnd_console_no_colors:
    class: logging.StreamHandler
    formatter: fmt_no_colors
    level: DEBUG
    stream: ext://sys.stdout
  hnd_console_colors:
    class: logging.StreamHandler
    formatter: fmt_colors
    level: DEBUG
    stream: ext://sys.stdout
  none:
    class: logging.NullHandler
loggers:
  '': # root logger
    handlers: [hnd_console_colors, hnd_file_root]
    level: INFO
  main:
    level: INFO
    propagate: True
  base_task:
    level: INFO
    propagate: True
  paths:
    level: DEBUG
    propagate: True
  list_view:
    level: INFO
    propagate: True
  galog_app:
    level: DEBUG
    propagate: True
  item_view_proxy:
    level: ERROR
    propagate: False