version: 0.1.0
rules:
  - name: OneLinerJsonKey
    pattern: >-
      [,{]+(\")((?:\\\"|[^\"])*)(\")\s*(:)
    priority: 900
    groups:
      - numbers: [1,3]
        highlighting:
          formatting:
            - thin
            - italic
      - numbers: [2]
        highlighting:
          formatting:
            - italic
      - numbers: [4]
        highlighting:
          formatting:
            - normal
  - name: MultilineJsonKey
    pattern: >-
      ^\s*(\")((?:\\\"|[^\"])*)(\")\s*(:)
    priority: 900
    groups:
      - numbers: [1,3]
        highlighting:
          formatting:
            - thin
            - italic
      - numbers: [2, 4]
        highlighting:
          formatting:
            - italic