version: 0.1.0
target:
  exe_path: __dist_min\galog\galog.exe
  args: []
  env:
    - name: 'PYTHONUNBUFFERED'
      value: '1'
  env_path_rm:
    - "*Python*"
  out_dir: __dist_min\galog.min
  run_timeout_sec: 5
  success_indicator:
    output: 'GALog initialized'
minimizers:
  qt_translation_files_removal:
    exclude_files: []
  unused_shared_libraries_removal:
    exclude_files:
      - '*\styles\qwindowsvistastyle.dll'
      - '*\imageformats\qsvg.dll'
      - '*\Qt5Svg.dll'
      - '*\_ctypes.pyd'
      - '*\python3.dll'
  external_strip_program:
    exe_path: strip.exe
    args: ['--strip-all']
    exclude_files: []
    fail_on_error: true
  external_packer_program:
    min_file_size_kb: 200
    exclude_files:
      - '*\platforms\*.dll'
      - '*\imageformats\*.dll'
      - '*\iconengines\*.dll'
    exe_path: upx.exe
    args: ['-9', '-q', '-f']
    fail_on_error: true
