version: 1
disable_existing_loggers: True
formatters:
  fmt_console:
    '()': 'logging.Formatter'
    format: '[%(process)d] %(asctime)s %(levelname)-8s %(name)-15s %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  fmt_colored_console:
    '()': 'ext://coloredlogs.ColoredFormatter'
    format: '[%(process)d] %(asctime)s %(levelname)-8s %(name)-15s %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
    field_styles:
      asctime:
        color: green
        bright: True
      name:
        color: blue
        bright: True
      levelname:
        color: cyan
        bold: True
      process:
        color: 116
    level_styles:
      info:
        color: cyan
        bright: True
      warning:
        color: 220
      error:
        color: red
      debug:
        color: green
      critical:
        color: red
        bold: True
handlers:
  hnd_console:
    class: logging.StreamHandler
    formatter: fmt_console
    level: NOTSET
    stream: ext://sys.stdout
  hnd_colored_console:
    class: logging.StreamHandler
    formatter: fmt_colored_console
    level: NOTSET
    stream: ext://sys.stdout
  none:
    class: logging.NullHandler
loggers:
  '': # root logger
    handlers: [hnd_colored_console]
    level: NOTSET
  main:
    level: INFO
  botocore:
    level: WARNING
  boto3:
    level: WARNING
  multipart:
    level: WARNING