version: 0.1.0
rules:
  - name: PackageName
    pattern: '[a-z0-9]+(\.[a-z0-9]+){2,}'
    priority: 500
    highlighting:
      formatting:
        - italic
        - underline
  - name: PackageNameWithActivity
    pattern: '([a-z0-9]+(?:\.[a-z0-9]+){2,})(\/)([a-z0-9]+(?:\.[a-z0-9]+){2,}\.\w+)'
    priority: 700
    groups:
      - numbers: [1,3]
        highlighting:
          formatting:
            - italic
            - underline
      - numbers: [2]
        highlighting:
          formatting:
            - thin