adb:
  ipAddr: '127.0.0.1'
  port: 5037
fonts:
  emoji: null
  logViewer:
    family: 'Roboto Mono'
    size: 14
  Standard:
    family: 'Roboto'
    size: 14
  Upsized:
    family: 'Roboto'
    size: 15
