adb:
  ipAddr: 127.0.0.1
  port: 5037
fonts:
  emoji: null
  logViewer:
    family: Roboto Mono
    size: 11
  standard:
    family: Roboto
    size: 11
  upsized:
    family: Roboto
    size: 12
emojiAddSpace: true
useEmoji: true
