adbServer:
  ipAddr: 127.0.0.1
  port: 5037
logViewer:
  liveReload: true
  textHighlighting: true
  showLineNumbers: false
fonts:
  emojiEnabled: true
  emojiAddSpace: true
  standard:
    family: Roboto
    size: 11
  logViewer:
    family: Roboto Mono
    size: 11
  menuBar:
    family: Roboto
    size: 11