name: Bump Version
permissions:
  contents: write
on:
  workflow_dispatch:
    inputs:
      update_type:
        description: Type of update to apply
        required: true
        default: 'minor'
        type: choice
        options:
          - major
          - minor
          - patch
jobs:
  bump_version:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PRIVATE_ACCESS_TOKEN }}
      - name: Set up git user
        run: |
           git config --global user.name "${{ vars.BOT_NAME }}"
           git config --global user.email "${{ vars.BOT_EMAIL }}"
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Increment version number
        run: |
          pip3 install bump2version~=1.0
          bump2version ${{ inputs.update_type }}
      - name: Push changes
        run: |
          git push --follow-tags
