name: Pull request validate

on:
  pull_request:
    branches: [main]
    types: [opened, edited]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title
        uses: deepakputhraya/action-pr-title@master
        with:
          regex: '(MAJOR|MINOR|PATCH): .+'
