name: Release
on:
  push:
    tags: ['*']
permissions:
  contents: write
jobs:
  windows_release:
    runs-on: windows-latest
    env:
      ARCHIVE_NAME: galog-${{ github.ref_name }}-win10-x64.zip
    steps:
      - name: Setup UPX
        uses: crazy-max/ghaction-upx@v3
        with:
          install-only: true
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build App
        run: |
          & .\scripts\windows\build.ps1
      - name: Compress bundle
        run: |
          Compress-Archive -Path .\__dist_release\galog\* -DestinationPath $env:ARCHIVE_NAME
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.ARCHIVE_NAME }}
  linux_release:
    runs-on: ubuntu-latest
    env:
      ARCHIVE_NAME: galog-${{ github.ref_name }}-linux-glibc2.31-x64.tar.gz
    container:
      image: ubuntu:20.04
      env:
        DEBIAN_FRONTEND: noninteractive
      options: >
        --workdir=/build
    steps:
      - name: Apt Update
        run: |
          apt update
      - name: Setup Packages
        run: |
          apt install -y \
            libgssapi-krb5-2 \
            libglib2.0-0 \
            libglib2.0-dev \
            libfontconfig1 \
            libfreetype6 \
            libxcb-xinerama0 \
            libxkbcommon-x11-0 \
            libxcb-icccm4 \
            libxcb-image0 \
            libxcb-keysyms1 \
            libxcb-randr0 \
            libxcb-render-util0 \
            libxcb-xinerama0 \
            libxcb-xfixes0 \
            libegl1-mesa \
            libxcb-shape0 \
            libdbus-1-3 \
            binutils \
            libgl1 \

      - name: Setup UPX
        run: |
          apt install -y upx
      - name: Setup Python
        run: |
          apt install -y python3.9
          apt install -y python3.9-venv
          apt install -y python3.9-dev
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build App
        run: |
          chmod +x ./scripts/linux/build.sh
          ./scripts/linux/build.sh
      - name: Compress bundle
        run: |
          tar -czf "${ARCHIVE_NAME}" -C "__dist_release" galog
      - name: Setup Github CLI
        uses: actions4gh/setup-gh@v1.0.2
        with:
          token: '' # prevent auth, avoid errors
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.ARCHIVE_NAME }}
